### ISSUE TITLE
Tracking issue for initial prototype

### ISSUE THREAD

**Issue by Max-Meldrum** [uwheel/datafusion-uwheel#1]
- [x] Implement initial ``UWheelOptimizer`` which implements ``QueryPlanner``
- [x] Make ``UWheelOptimizer`` work for an example query
- [ ] Support temporal filtering/pruning using ``MinMax`` wheels
- [ ] Support custom aggregation wheels (e.g., SUM(fare_amount))
